--- #YAML:1.0
name:               Spreadsheet-XlateExcel
version:            0.02
abstract:           Trigger a callback subroutine on each row of an Excel spreadsheet
author:
    - Xavier Caron <xav@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp::Assert::More:   1.12
    Spreadsheet::ParseExcel:  0.58
    Test::Differences:    0.5
    Test::More:           0.94
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
